regions:
  - eu-west-3
  - global

account-blocklist:
  - "000000000000"

accounts:
  "745738989517":
    filters:
      IAMUser:
        - property: "UserName"
          type: "glob"
          value: "alberto"
      IAMUserPolicyAttachment:
        - property: "UserName"
          type: "glob"
          value: "alberto"
      IAMRole:
        - property: "RoleName"
          type: "glob"
          value: "alberto"
        - property: "RoleName"
          type: "glob"
          value: "admin"

resource-types:
  excludes:
    - IAMUserAccessKey
    - IAMGroup
    - CertificateManager
    - ACMCertificate
    - ACMCertificateValidation
    - Route53
    - Route53Zone
